### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by fgr1986** [danieljfarrell/FVM#2]
Hi Daniel.

I have developed a framework where one of the validation scripts is based on your FVM notes.
I would like to open source our framework for other researchers to use under BSD 3 license.
In the process of cleaning code, references etc, I noticed that your FVM project does not have any license, which may be a problem to open source it from my side.
If you do not mind me asking: could it be possible to add a license to your github?

That would help the development of other projects based on your very useful script.

Thanks a lot.
Regards

**Comment by danieljfarrell** [comment]
OK that's done. Also invited you as a collaborator should you need to do anything else with this project. I can't see myself doing anything with it now.

**Comment by fgr1986** [comment]
Thanks

**Comment by danieljfarrell** [comment]
I meant to say, let me know when your project is published, it will be cool to have a look. 👍

**Comment by fgr1986** [comment]
Thanks @danieljfarrell we just released it at https://github.com/ARM-software/mram_simulation_framework/
